### ISSUE TITLE
Question: storable data max size

### ISSUE THREAD

**Issue by max-kim** [emeraldsanto/react-native-encrypted-storage#25]
What is the storable data max size allowed?

**Comment by emeraldsanto** [comment]
There [doesn't seem to be one](https://stackoverflow.com/questions/4925194/whats-the-maximum-size-for-an-android-shared-preference-value?answertab=oldest#tab-top) on Android since this is using `EncryptedSharedPreferences`.

However it looks like the [limit is not so well known on iOS](https://stackoverflow.com/questions/13488793/is-there-any-length-limit-of-string-stored-in-keychain).
