### ISSUE TITLE
Library cannot be used on a Windows development machine

### ISSUE THREAD

**Issue by DOFandersolsen** [emeraldsanto/react-native-encrypted-storage#30]
Hi,

I just installed the module today according to the instructions and attempted to build and run the app on an Android simulator.

However, I get the following error in the console:

```
[Mon Nov 02 2020 11:06:52.628]  BUNDLE  ./index.js

[Mon Nov 02 2020 11:07:03.250]  ERROR    Error: RNEncryptedStorage is undefined
[Mon Nov 02 2020 11:07:03.252]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Mon Nov 02 2020 11:07:03.252]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

According to your comment [here](https://www.reddit.com/r/reactnative/comments/f42rfa/i_published_a_secure_alternative_to_asyncstorage/fsp2g5m/), I need to build the pods for the iOS project, but since I'm on my Windows machine, I don't have access to Xcode. 

Shouldn't this error only occur if I were running the iOS app and not the Android app ?

**Comment by emeraldsanto** [comment]
Hello, that's right the iOS specific steps shouldn't be necessary in this case since you're only running the Android app. 

I don't think this has anything to do with the operating system you're using, which React Native version are you on? 

For <= 0.59 you will need to run:

`react-native link react-native-encrypted-storage`

Otherwise auto linking should work on it's own.

**Comment by DOFandersolsen** [comment]
From `package.json`:
```json
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-encrypted-storage": "^3.0.0"
```
